version: '3.8'

services:
  inventory:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - PORT=${PORT}
      - SECRET=${SECRET}
      - MONGODB_URL=${MONGODB_URL}
    volumes:
      - api:/inventory/api
    depends_on:
      - mongodb
    networks:
      clusternetwork:
        ipv4_address: 172.16.0.12
      
  mongodb:
    image: mongo:latest
    container_name: my-mongodb
    # restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      # MONGO_INITDB_ROOT_USERNAME: admin
      # MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_DATABASE: inventory
    networks:
      clusternetwork:
        ipv4_address: 172.16.0.14


volumes:
  api:
    name: api-app
  mongodb_data:
    name: my-mongodb-data

networks:
  clusternetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/24